modLoader = "javafml"
loaderVersion = "[0,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "Quick Test World"
authors = "Me!"
description = '''
A minecraft mod that adds a new world type "testworld"
'''
#logoFile = ""

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"